blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url('', include('myblog.urls')),
    url('', include('comments.urls')),
    path('admin/', admin.site.urls),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.conf.urls import url
from . import views;

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<pk>[0-9])/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category,name='category')
]

comments/models.py
from django.db import models
from myblog.models import Post
# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 文章摘要
    excerpt = models.CharField(max_length=200, blank=True)

    # 类目
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 标签
    tags = models.ManyToManyField(Tag, blank=True)
    # 作者
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Comment
from django.urls import reverse
from .forms import CommentForm
from django.core import serializers
import json
from myblog.models import Post


# Create your views here.
def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            # 因为有外键 所以不自动提交 等关联完外键之后再提交 所以用commit= false
            comment.post = post

            comment.save()
            return redirect(reverse('blog:detail', kwargs={'pk': post.pk}))

        else:
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'myblog/detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(reverse('blog:detail', kwargs={'pk': post.pk}))

myblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Post, Tag
from comments.forms import CommentForm
from django.views.generic.list import ListView
from django.http import HttpResponse
from django.contrib.auth.models import User
import markdown
from django.core import serializers


# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'myblog/index.html', context={'post_list': post_list})


def detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    post_detail.body = '''# 一级标题

## 二级标题

### 三级标题

- 列表项1
- 列表项2
- 列表项3

> 这是一段引用

​```
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    return render(request, 'blog/detail.html', context={'post': post})
​``` '''
    post_detail.body = markdown.markdown(post_detail.body,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])
    form = CommentForm()
    comment_list = post_detail.comment_set.all()
    context = {'postDetail': post_detail,
               'form': form,
               'comment_list': comment_list}
    return render(request, 'myblog/detail.html', context)


def archives(request, year, month):
    post_list = Post.objects.filter(
        created_time__year=year,
        created_time__month=month).order_by('-created_time')
    return render(request, 'myblog/index.html', context={"post_list": post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'myblog/index.html', context={"post_list": post_list})


def createPost(request):
    cate = request.POST['category']
    print(cate)
    category = Category.objects.create(name=cate)
    post = Post()
    post.title = request.POST['title']
    post.excerpt = request.POST['excerpt']
    post.body = request.POST['body']
    post.author = User.objects.filter(pk=1)
    post.category = category
    post.save()

templates/base.html
{% load myblog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>test</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'myblog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'myblog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'myblog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/pace.min.js' %}"></script>
    <script src="{% static 'myblog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html">test</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as data_list %}
                    <ul>
                        {% for data in  data_list %}
                            <li>
                                <a href="{% url 'blog:archives' data.year data.month %}">{{ data.year }} 年 {{ data.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categorys as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count"></span></a>
                            </li>
                        {% empty %}
                            暂无分类记录
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright"> 2018 - 采集自<a href="http://www.cssmoban.com/"
                                                   target="_blank" title="模板之家">模板之家</a>
                    - 由杨丰瑞修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'myblog/js/script.js' %}"></script>

</body>
</html>

templates/myblog/create.html
{% extends 'base.html' %}
{% block main %}
        <hr>
        <h3>创建文章</h3>
        <form action="{% url 'comments:post_comment' postDetail.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="category">category:</label>
                    <input type="text" class="form-control" id="category" name="category" placeholder="category">
                </div>
                <div class="col-md-4">
                    <label for="title">title:</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="title">
                </div>
                <div>
                    <label for="excerpt">excerpt:</label>
                    <input type="text" class="form-control" id="excerpt" name="excerpt" placeholder="excerpt">
                </div>
                <div class="col-md-12">
                    <label for="body">body:</label>
                    <textarea class="form-control" rows="3" id="body" name="body"></textarea>
                    <button type="submit" class="btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
{% endblock main %}

templates/myblog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-{{ postDetail.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ postDetail.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ postDetail.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ postDetail.created_time }}">{{ postDetail.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ postDetail.author }}</a></span>
                <span class="comments-link"><a href="#">4 评论</a></span>
                <span class="views-count"><a href="#">588 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ postDetail.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' postDetail.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">

            <ul class="comment-list list-unstyled">
            <h3>评论列表，共 <span>{{ comment_list|length }}</span> 条评论</h3>
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <span >{{ comment.email }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>

                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    <h3>暂无评论</h3>
                {% endfor %}
            </ul>

        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/myblog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>六哥的后花园</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'myblog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'myblog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'myblog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/pace.min.js' %}"></script>
    <script src="{% static 'myblog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html">六哥的后花园~  六哥的说唱让你忘了爱</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
            {% block main %}
                {% for post in post_list %}
                    <article class="post post-{{ post.pk }}">
                       <header class="entry-header">
                           <h1 class="entry-title">
                               <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                           </h1>
                           <div class="entry-meta">
                               <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                               <span class="post-date"><a href="#"><time class="entry-date"
                                                                         datetime={{ post.created_time }}>{{ post.created_time }}</time></a></span>
                               <span class="post-author"><a href="#">{{ post.author }}</a></span>
                               <span class="comments-link"><a href="#">4 评论</a></span>
                               <span class="views-count"><a href="#">588 阅读</a></span>
                           </div>
                       </header>
                       <div class="entry-content clearfix">
                           <p>{{ post.excerpt }}</p>
                           <div class="read-more cl-effect-14">
                               <a href="{% url 'blog:detail' post.pk %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                           </div>
                       </div>
                    </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
            {% endblock main %}
            </main>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright"> 2018 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由杨丰瑞修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'myblog/js/script.js' %}"></script>

</body>
</html>